# Generated by Django 5.0.2 on 2024-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_member_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="joineddate",
            field=models.IntegerField(null=True),
        ),
    ]
