# Generated by Django 5.0.2 on 2024-02-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_member_joineddate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="joineddate",
            field=models.DateField(null=True),
        ),
    ]
